import { z } from "zod";

export const COUNTRY_CODES = [
  { label: "United States (+1)", code: "+1" },
  { label: "Canada (+1)", code: "+1" },
  { label: "United Kingdom (+44)", code: "+44" },
  { label: "Australia (+61)", code: "+61" },
  { label: "New Zealand (+64)", code: "+64" },
  { label: "Ireland (+353)", code: "+353" },
  { label: "South Africa (+27)", code: "+27" },
  { label: "Austria (+43)", code: "+43" },
  { label: "Belgium (+32)", code: "+32" },
  { label: "Brazil (+55)", code: "+55" },
  { label: "Chile (+56)", code: "+56" },
  { label: "China (+86)", code: "+86" },
  { label: "Colombia (+57)", code: "+57" },
  { label: "Czech Republic (+420)", code: "+420" },
  { label: "Denmark (+45)", code: "+45" },
  { label: "Egypt (+20)", code: "+20" },
  { label: "Finland (+358)", code: "+358" },
  { label: "France (+33)", code: "+33" },
  { label: "Germany (+49)", code: "+49" },
  { label: "Greece (+30)", code: "+30" },
  { label: "India (+91)", code: "+91" },
  { label: "Indonesia (+62)", code: "+62" },
  { label: "Israel (+972)", code: "+972" },
  { label: "Italy (+39)", code: "+39" },
  { label: "Japan (+81)", code: "+81" },
  { label: "Kenya (+254)", code: "+254" },
  { label: "Malaysia (+60)", code: "+60" },
  { label: "Mexico (+52)", code: "+52" },
  { label: "Netherlands (+31)", code: "+31" },
  { label: "Nigeria (+234)", code: "+234" },
  { label: "Norway (+47)", code: "+47" },
  { label: "Peru (+51)", code: "+51" },
  { label: "Philippines (+63)", code: "+63" },
  { label: "Poland (+48)", code: "+48" },
  { label: "Portugal (+351)", code: "+351" },
  { label: "Singapore (+65)", code: "+65" },
  { label: "South Korea (+82)", code: "+82" },
  { label: "Spain (+34)", code: "+34" },
  { label: "Sweden (+46)", code: "+46" },
  { label: "Switzerland (+41)", code: "+41" },
  { label: "Thailand (+66)", code: "+66" },
  { label: "United Arab Emirates (+971)", code: "+971" },
  { label: "Argentina (+54)", code: "+54" },
] as const;

export const volunteerSchema = z.object({
  firstName: z.string().min(1, "First name is required"),
  lastName: z.string().min(1, "Last name is required"),
  email: z.string().email("Please enter a valid email"),
  phoneCountryCode: z.string().min(1, "Please select a country code"),
  phone: z.string().min(1, "Phone number is required"),
  consent: z.boolean().refine((val) => val === true, {
    message: "Please acknowledge the application consent to submit",
  }),
});

export type VolunteerFormData = z.infer<typeof volunteerSchema>;
